### ISSUE TITLE
Install ubuntu 16.04

### ISSUE THREAD

**Issue by jeromim** [marshallford/seedbox-installer#1]
http://www.itzgeek.com/how-tos/linux/ubuntu-how-tos/install-utorrent-on-ubuntu-16-04.html

Complement seedbox.

**Comment by marshallford** [comment]
Thanks for the link. If you haven't noticed this project is essentially unmaintained. These days I would highly recommend deluged and deluge-webui. Last I checked Deluge has a similar feature list and doesn't sell your data like uTorrent does. You can get up to date Deluge packages via a ppa assuming you're running Ubuntu server. Note: You will need to setup Deluge to start on boot manually. See: http://dev.deluge-torrent.org/wiki/UserGuide/Service.
